
import type { AnalysisResults, AnalysisStage, ResumeProfile, JobRoleRecommendation, MarketResearchResult, SkillGap, PlacementRisk, SalaryEstimate, RoadmapStep } from '@/types/analysis';
import { parseResume } from './agents/resume-parser';
import { analyzeJobRoles } from './agents/job-role-analyzer';
import { researchMarket } from './agents/market-researcher';
import { analyzeSkillGaps } from './agents/skill-gap-analyzer';
import { predictPlacementRisk } from './agents/placement-risk';
import { estimateSalaries } from './agents/salary-estimator';
import { buildCareerRoadmap } from './agents/career-roadmap';
import { db } from './db';

/**
 * Progress callback type - used to emit SSE events to the client
 */
export type ProgressCallback = (
  stage: AnalysisStage,
  progress: number,
  message: string
) => void;

/**
 * Stage progress mapping - defines the progress percentage at each stage
 */
const STAGE_PROGRESS: Record<AnalysisStage, { start: number; end: number }> = {
  idle: { start: 0, end: 0 },
  uploading: { start: 0, end: 5 },
  ocr: { start: 5, end: 15 },
  parsing: { start: 15, end: 25 },
  'analyzing-roles': { start: 25, end: 35 },
  'researching-market': { start: 35, end: 50 },
  'analyzing-skills': { start: 50, end: 65 },
  'predicting-risk': { start: 65, end: 75 },
  'estimating-salary': { start: 75, end: 90 },
  'building-roadmap': { start: 90, end: 100 },
  complete: { start: 100, end: 100 },
  error: { start: 0, end: 0 },
};

// Default fallback values for each stage
const EMPTY_PROFILE: ResumeProfile = {
  name: '', email: '', phone: '', location: '', summary: '',
  skills: [], education: [], experience: [], certifications: [], languages: [], projects: [],
};

const DEFAULT_RISK: PlacementRisk = {
  overallRisk: 'Medium',
  overallScore: 50,
  withinThreeMonths: 20,
  withinSixMonths: 45,
  withinTwelveMonths: 70,
  strengths: ['Profile available for analysis'],
  weaknesses: ['More details needed for accurate assessment'],
  explanation: 'Placement risk assessment based on available data.',
};

/**
 * Delay helper to avoid rate limiting
 */
function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Sends a notification to Telegram with the analysis summary
 */
async function sendTelegramNotification(results: AnalysisResults) {
  const botToken = process.env.TELEGRAM_BOT_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;

  if (!botToken || !chatId) {
    console.log('[analysis-engine] Telegram notification skipped: Bot token or chat ID missing');
    return;
  }

  const { profile, placementRisk } = results;
  const message = `
≡ Career Intelligence Report Complete! ≡

👤 *Candidate:* ${profile.name || 'Unknown'}
📧 *Email:* ${profile.email || 'N/A'}

📊 *Placement Risk Assessment:*
- Overall Risk: ${placementRisk.overallRisk}
- Placement Score: ${placementRisk.overallScore}/100
- 3 Months Prob: ${placementRisk.withinThreeMonths}%
- 6 Months Prob: ${placementRisk.withinSixMonths}%

💼 *Top Job Roles:*
${results.jobRoles.slice(0, 3).map((r, i) => `${i + 1}. ${r.role} (${r.matchScore}%)`).join('\n')}

💡 *Action Plan:*
- Critical Gaps: ${results.skillGaps.filter(g => g.importance === 'Critical').length}
- Roadmap Phases: ${results.roadmap.length}

Generated by AI Career Intelligence Platform
  `.trim();

  try {
    const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: message,
        parse_mode: 'Markdown',
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      console.error('[analysis-engine] Telegram notification failed:', error);
    } else {
      console.log('[analysis-engine] Telegram notification sent successfully');
    }
  } catch (error) {
    console.error('[analysis-engine] Telegram notification failed:', error);
  }
}

/**
 * Main orchestrator that runs all AI agents in sequence,
 * emitting progress events through a callback.
 * NEVER throws — always returns results with fallbacks for failed stages.
 */
export async function runAnalysis(
  fileBuffer: Buffer,
  fileName: string,
  mimeType: string,
  onProgress: ProgressCallback,
  userId?: string
): Promise<AnalysisResults> {
  // Top-level try/catch: this function MUST NEVER throw
    try {
      console.log(`[analysis-engine] Starting analysis for ${fileName} (${mimeType}, ${(fileBuffer.length / 1024).toFixed(1)}KB)`);

      // Log activity
      if (userId) {
        await db.userActivity.create({
          data: {
            type: 'analysis',
            detail: `Started analysis for ${fileName}`,
            userId: userId
          }
        }).catch(e => console.error('Failed to log activity:', e));
      }

      const emitProgress = (stage: AnalysisStage, fraction: number, message: string) => {
      const { start, end } = STAGE_PROGRESS[stage];
      const progress = Math.round(start + (end - start) * fraction);
      onProgress(stage, progress, message);
    };

    // Initialize all results with defaults
    let profile: ResumeProfile = EMPTY_PROFILE;
    let jobRoles: JobRoleRecommendation[] = [];
    let marketResearch: MarketResearchResult[] = [];
    let skillGaps: SkillGap[] = [];
    let placementRisk: PlacementRisk = DEFAULT_RISK;
    let salaryEstimates: SalaryEstimate[] = [];
    let roadmap: RoadmapStep[] = [];

    // ============================
    // Stage 1: Resume Parsing
    // ============================
    try {
      emitProgress('parsing', 0, 'Reading resume file...');
      console.log('[analysis-engine] Stage 1/7: Resume parsing');
      
      let extractedText = '';
      const isPdf = mimeType === 'application/pdf' || fileName.toLowerCase().endsWith('.pdf');
      const isDocx = mimeType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' || fileName.toLowerCase().endsWith('.docx');
      const isImage = mimeType.startsWith('image/') || /\.(png|jpe?g|webp)$/i.test(fileName);
      const require = (await import('module')).createRequire(import.meta.url);
      
      console.log('=== PIPELINE LOG START ===');
      console.log('1. Uploaded filename:', fileName);
      console.log('2. File type:', mimeType);
      
      try {
        if (isPdf) {
          console.log('[analysis-engine] Extracting text from PDF...');
          const pdf = require('pdf-parse-fork');
          const data = await pdf(fileBuffer);
          extractedText = data.text;
        } else if (isDocx) {
          console.log('[analysis-engine] Extracting text from DOCX...');
          const mammoth = require('mammoth');
          const result = await mammoth.extractRawText({ buffer: fileBuffer });
          extractedText = result.value;
        } else if (isImage) {
          console.log('[analysis-engine] Image file detected, skipping OCR (fallback mode)...');
          extractedText = `Uploaded image file: ${fileName}. For full analysis, please upload a PDF or DOCX resume.`;
        } else {
          extractedText = fileBuffer.toString('utf-8');
        }
      } catch (extractErr) {
        console.warn('[analysis-engine] Text extraction failed, using fallback text:', extractErr);
        extractedText = `Uploaded file: ${fileName}. Text extraction failed, using basic fallback analysis.`;
      }
      
      console.log('3. Extracted text length:', extractedText.length);
      console.log('4. First 1000 characters of extracted text:', extractedText.slice(0, 1000));
      
      // Use GROQ-based LLM parsing
      try {
        profile = await parseResume(fileBuffer, fileName, mimeType, emitProgress, userId);
      } catch (parseErr) {
        console.warn('[analysis-engine] AI parse failed, using manual extraction:', parseErr);
        profile = { ...EMPTY_PROFILE, summary: extractedText.slice(0, 500) };
        const commonSkills = ['JavaScript', 'Python', 'React', 'Node.js', 'CSS', 'HTML', 'SQL', 'Git', 'Docker', 'AWS'];
        profile.skills = commonSkills.filter(skill => extractedText.toLowerCase().includes(skill.toLowerCase()));
      }
      
      console.log('5. Parsed skills:', profile.skills);
      console.log('6. Parsed education:', profile.education);
      console.log('7. Parsed experience:', profile.experience);
      console.log(`[analysis-engine] Resume parsed: name="${profile.name}", skills=${profile.skills.length}, experience=${profile.experience.length}`);
      emitProgress('parsing', 1, 'Resume parsed successfully');
    } catch (err) {
      console.error('[analysis-engine] Resume parsing failed, using fallback:', err);
      profile = { ...EMPTY_PROFILE, summary: 'Resume could not be fully parsed. Providing analysis based on limited data.' };
      emitProgress('parsing', 1, 'Resume parsing encountered issues, continuing...');
    }

    // Delay between stages to avoid rate limiting (2500ms)
    await delay(2500);

    // ============================
    // Stage 2: Job Role Analysis
    // ============================
    try {
      emitProgress('analyzing-roles', 0, 'Analyzing career fit...');
      console.log('[analysis-engine] Stage 2/7: Job role analysis');
      jobRoles = await analyzeJobRoles(profile);
      console.log(`[analysis-engine] Job roles identified: ${jobRoles.map((r) => r.role).join(', ')}`);
      emitProgress('analyzing-roles', 1, 'Job roles identified');
    } catch (err) {
      console.error('[analysis-engine] Job role analysis failed, using fallback:', err);
      jobRoles = [{
        role: 'Software Developer',
        matchScore: 50,
        reason: 'Default recommendation based on available profile data. A more specific analysis requires additional details.',
        requiredSkills: ['Programming', 'Problem Solving', 'Communication', 'Teamwork'],
        matchedSkills: profile.skills.slice(0, 3),
        growthPotential: 'Medium',
      }];
      emitProgress('analyzing-roles', 1, 'Using default role recommendations...');
    }

    await delay(2500);

    // ============================
    // Stage 3: Market Research
    // ============================
    try {
      emitProgress('researching-market', 0, 'Researching job market trends...');
      console.log('[analysis-engine] Stage 3/7: Market research');
      const roleNames = jobRoles.map((r) => r.role);
      marketResearch = await researchMarket(roleNames);
      console.log(`[analysis-engine] Market research complete: ${marketResearch.length} roles analyzed`);
      emitProgress('researching-market', 1, 'Market research complete');
    } catch (err) {
      console.error('[analysis-engine] Market research failed, using fallback:', err);
      marketResearch = jobRoles.map((r) => ({
        role: r.role,
        demandLevel: 'Medium' as const,
        hiringCompanies: ['Google', 'Microsoft', 'Amazon'],
        averageOpenings: '5,000+',
        trend: 'Growing' as const,
        topLocations: ['San Francisco', 'New York', 'Seattle'],
        keyInsight: 'Market research data is currently unavailable. This role generally has steady demand in the tech industry.',
      }));
      emitProgress('researching-market', 1, 'Using estimated market data...');
    }

    await delay(2500);

    // ============================
    // Stage 4: Skill Gap Analysis
    // ============================
    try {
      emitProgress('analyzing-skills', 0, 'Identifying skill gaps...');
      console.log('[analysis-engine] Stage 4/7: Skill gap analysis');
      skillGaps = await analyzeSkillGaps(profile, jobRoles);
      console.log(`[analysis-engine] Skill gaps identified: ${skillGaps.length} gaps found`);
      emitProgress('analyzing-skills', 1, 'Skill gaps identified');
    } catch (err) {
      console.error('[analysis-engine] Skill gap analysis failed, using fallback:', err);
      const missingSkills = jobRoles
        .flatMap((r) => r.requiredSkills)
        .filter((s) => !profile.skills.some((ps) => ps.toLowerCase().includes(s.toLowerCase()) || s.toLowerCase().includes(ps.toLowerCase())));
      const uniqueMissing = [...new Set(missingSkills)].slice(0, 8);
      skillGaps = uniqueMissing.map((skill) => ({
        skill,
        importance: 'Important' as const,
        category: 'Technical',
        learningDifficulty: 'Medium' as const,
        estimatedTimeToLearn: '1-3 months',
        resources: ['Online courses', 'Documentation', 'Practice projects'],
      }));
      emitProgress('analyzing-skills', 1, 'Using estimated skill gaps...');
    }

    await delay(2500);

    // ============================
    // Stage 5: Placement Risk
    // ============================
    try {
      emitProgress('predicting-risk', 0, 'Calculating placement risk...');
      console.log('[analysis-engine] Stage 5/7: Placement risk prediction');
      placementRisk = await predictPlacementRisk(profile, jobRoles, skillGaps);
      console.log(`[analysis-engine] Placement risk: ${placementRisk.overallRisk} (score: ${placementRisk.overallScore})`);
      emitProgress('predicting-risk', 1, 'Placement risk calculated');
    } catch (err) {
      console.error('[analysis-engine] Placement risk prediction failed, using fallback:', err);
      const avgScore = jobRoles.length > 0
        ? jobRoles.reduce((sum, r) => sum + r.matchScore, 0) / jobRoles.length
        : 50;
      placementRisk = {
        overallRisk: avgScore >= 70 ? 'Low' : avgScore >= 40 ? 'Medium' : 'High',
        overallScore: Math.round(avgScore),
        withinThreeMonths: Math.max(5, Math.round(avgScore - 30)),
        withinSixMonths: Math.max(15, Math.round(avgScore - 10)),
        withinTwelveMonths: Math.min(95, Math.round(avgScore + 15)),
        strengths: profile.skills.slice(0, 4).map((s) => `Skill: ${s}`),
        weaknesses: skillGaps.slice(0, 3).map((g) => `Missing: ${g.skill}`),
        explanation: 'Placement risk assessment generated from available data. A detailed AI assessment could not be completed at this time.',
      };
      emitProgress('predicting-risk', 1, 'Using estimated placement risk...');
    }

    await delay(2500);

    // ============================
    // Stage 6: Salary Estimation
    // ============================
    try {
      emitProgress('estimating-salary', 0, 'Estimating salary ranges...');
      console.log('[analysis-engine] Stage 6/7: Salary estimation');
      salaryEstimates = await estimateSalaries(profile, jobRoles);
      console.log(`[analysis-engine] Salary estimates complete: ${salaryEstimates.length} roles estimated`);
      emitProgress('estimating-salary', 1, 'Salary estimates ready');
    } catch (err) {
      console.error('[analysis-engine] Salary estimation failed, using fallback:', err);
      salaryEstimates = jobRoles.map((role) => ({
        role: role.role,
        entryLevel: { min: 45000, max: 70000, median: 57000 },
        midLevel: { min: 70000, max: 110000, median: 88000 },
        seniorLevel: { min: 110000, max: 170000, median: 138000 },
        currency: 'USD',
        confidenceLevel: 'Low' as const,
        factors: ['General market estimate', 'Location not specified', 'Experience level varies'],
      }));
      emitProgress('estimating-salary', 1, 'Using estimated salary data...');
    }

    await delay(2500);

    // ============================
    // Stage 7: Career Roadmap
    // ============================
    try {
      emitProgress('building-roadmap', 0, 'Building career roadmap...');
      console.log('[analysis-engine] Stage 7/7: Career roadmap');
      roadmap = await buildCareerRoadmap(profile, jobRoles, skillGaps, placementRisk);
      console.log(`[analysis-engine] Career roadmap built: ${roadmap.length} phases`);
      emitProgress('building-roadmap', 1, 'Career roadmap complete');
    } catch (err) {
      console.error('[analysis-engine] Career roadmap failed, using fallback:', err);
      roadmap = [
        {
          phase: 1, title: 'Foundation Building', duration: '1-2 months',
          tasks: skillGaps.filter((g) => g.importance === 'Critical').slice(0, 4).map((g) => `Learn ${g.skill}`) || ['Identify and learn critical missing skills'],
          milestone: 'Build foundational skills for target roles', priority: 'Critical' as const,
        },
        {
          phase: 2, title: 'Skills Development', duration: '2-3 months',
          tasks: skillGaps.filter((g) => g.importance === 'Important').slice(0, 4).map((g) => `Develop proficiency in ${g.skill}`) || ['Practice and apply new skills'],
          milestone: 'Achieve working proficiency in key areas', priority: 'High' as const,
        },
        {
          phase: 3, title: 'Project Portfolio', duration: '1-2 months',
          tasks: ['Build portfolio projects', 'Document achievements', 'Get peer feedback'],
          milestone: 'Complete 2-3 portfolio-ready projects', priority: 'High' as const,
        },
        {
          phase: 4, title: 'Job Search & Interviews', duration: '1-2 months',
          tasks: ['Optimize resume', 'Practice interviews', 'Apply to positions', 'Network professionally'],
          milestone: 'Secure interviews for target roles', priority: 'Medium' as const,
        },
      ];
      emitProgress('building-roadmap', 1, 'Using default roadmap...');
    }

    // ============================
    // Assemble Final Results
    // ============================
    const results: AnalysisResults = {
      profile,
      jobRoles,
      marketResearch,
      skillGaps,
      placementRisk,
      salaryEstimates,
      roadmap,
    };

    console.log('[analysis-engine] Analysis complete!');
    onProgress('complete', 100, 'Analysis complete!');

    // Save report and resume file to database if userId is provided
    if (userId) {
      try {
        console.log(`[analysis-engine] Saving report for user ${userId}`);
        
        // First, mark all existing resumes for this user as not latest
        await db.resume.updateMany({
          where: { userId, isLatest: true },
          data: { isLatest: false }
        });
        
        // Find the highest version number for this user
        const latestResume = await db.resume.findFirst({
          where: { userId },
          orderBy: { version: 'desc' },
          select: { version: true }
        });
        const nextVersion = (latestResume?.version || 0) + 1;
        
        // Create the report
        const savedReport = await db.report.create({
          data: {
            userId,
            candidateName: profile.name || 'Unknown',
            resumeData: profile as any,
            analysisResult: results as any,
            overallScore: placementRisk.overallScore,
            placementRisk: placementRisk.overallRisk,
          },
        });
        results.id = savedReport.id;
        console.log('[analysis-engine] Report saved successfully with ID:', savedReport.id);
        
        // Create the resume entry with version tracking
        const savedResume = await db.resume.create({
          data: {
            userId,
            reportId: savedReport.id,
            fileName,
            fileType: mimeType,
            fileSize: fileBuffer.length,
            fileData: fileBuffer,
            version: nextVersion,
            isLatest: true
          }
        });
        console.log('[analysis-engine] Resume saved successfully with ID:', savedResume.id, 'Version:', nextVersion);

        // Log completion activity
        await db.userActivity.create({
          data: {
            type: 'report_saved',
            detail: `Generated report ${savedReport.id} and resume v${nextVersion}`,
            userId: userId
          }
        }).catch(e => console.error('Failed to log activity:', e));
      } catch (dbError) {
        console.error('[analysis-engine] Failed to save report to database:', dbError);
        // Log DB error
        await db.errorLog.create({
          data: {
            type: 'backend',
            message: `Failed to save report: ${dbError instanceof Error ? dbError.message : String(dbError)}`,
            userId: userId
          }
        }).catch(() => {});
      }
    }

    // Trigger Telegram notification asynchronously (don't wait for it)
    sendTelegramNotification(results).catch((err) =>
      console.error('[analysis-engine] Async Telegram notification error:', err)
    );

    return results;
  } catch (topLevelError) {
    // This should never happen, but as a safety net we catch it
    // so the function NEVER throws
    console.error('[analysis-engine] UNEXPECTED top-level error in runAnalysis:', topLevelError);
    onProgress('error', 0, 'An unexpected error occurred during analysis. Partial results may be available.');

    // Log unexpected error
    await db.errorLog.create({
      data: {
        type: 'ai',
        message: `Unexpected analysis error: ${topLevelError instanceof Error ? topLevelError.message : String(topLevelError)}`,
        stack: topLevelError instanceof Error ? topLevelError.stack : undefined,
        userId: userId
      }
    }).catch(() => {});

    // Return minimal fallback results
    return {
      profile: EMPTY_PROFILE,
      jobRoles: [],
      marketResearch: [],
      skillGaps: [],
      placementRisk: DEFAULT_RISK,
      salaryEstimates: [],
      roadmap: [],
    };
  }
}
